---
- name: manage ACLs
  ansible.posix.acl:
    path: "{{ item.path }}"
    recursive: "{{ item.recursive | default(omit) }}"
    default: "{{ item.default | default(omit) }}"
    recalculate_mask: "{{ item.recalculate_mask | default(omit) }}"
    entity: "{{ item.entity | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    follow: "{{ item.follow | default(omit) }}"
    etype: "{{ item.etype | default(omit) }}"
    entry: "{{ item.entry | default(omit) }}"
    permissions: "{{ item.permissions | default(omit) }}"
  loop: "{{ acl_acls }}"
  loop_control:
    label: "{{ item.path }}"

- name: apply default ACLs directly
  ansible.posix.acl:
    path: "{{ item.path }}"
    recursive: "{{ item.recursive | default(omit) }}"
    default: false
    recalculate_mask: "{{ item.recalculate_mask | default(omit) }}"
    entity: "{{ item.entity | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    follow: "{{ item.follow | default(omit) }}"
    etype: "{{ item.etype | default(omit) }}"
    entry: "{{ item.entry | default(omit) }}"
    permissions: "{{ item.permissions | default(omit) }}"
  when:
    - acl_apply_defaults
    - item.default | default(false)
  loop: "{{ acl_acls }}"
  loop_control:
    label: "{{ item.path }}"
